name = "bay-url"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "bay-url-db"
database_id = "92c8b9ca-ea37-4180-87cc-8bbbdbcc3d06"

